### ISSUE TITLE
[noob] keep getting: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lettersforword365** [Shpota/github-activity-generator#18]
im new to github and wanted to try this.

running ubuntu, installed python via apt and opened terminal inside the main folder containing the python scripts

made an empty repo and typed:
python contribute.py --repository=oneoftheprivategithubemails@noreply.github.com:https://github.com/lettersforword365/testpy.git

am i doing something wrong?

im getting:

> Traceback (most recent call last):
>   File "contribute.py", line 111, in <module>
>     main()
>   File "contribute.py", line 28, in main
>     run(['git', 'init'])
>   File "contribute.py", line 62, in run
>     Popen(commands).wait()
>   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by lettersforword365** [comment]
turns out i didnt set up git and what not
