### ISSUE TITLE
Cannot find the file (Windows)

### ISSUE THREAD

**Issue by Sautenich** [Shpota/github-activity-generator#26]
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\GH_activity\github-activity-generator-main\github-activity-generator-main\contribute.py", line 128, in <module>
    main()
  File "C:\Users\admin\Desktop\GH_activity\github-activity-generator-main\github-activity-generator-main\contribute.py", line 32, in main
    run(['git', 'init', '-b', 'main'])
  File "C:\Users\admin\Desktop\GH_activity\github-activity-generator-main\github-activity-generator-main\contribute.py", line 67, in run
    Popen(commands).wait()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Cannot find the file
PS C:\Users\admin\Desktop\GH_activity\github-activity-generator-main\github-activity-generator-main>

**Comment by Sautenich** [comment]
Ok, i did install git on windows by the wrong way. Use this link to install: https://git-scm.com/download/win

<3
