### ISSUE TITLE
[Bug] Getting empty "" directory 

### ISSUE THREAD

**Issue by mandliyarajendra11** [Shpota/github-activity-generator#42]
I'm encountering an error related to the directory:

```
Traceback (most recent call last):
  File "xyz\New folder\contribute.py", line 128, in <module>
    main()
  File "xyz\New folder\contribute.py", line 30, in main
    os.mkdir(directory)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

The issue seems to stem from this line:
```python
directory = repository[start:end]
```

Is there a way I can work on fixing this issue?

**Comment by Shpota** [comment]
@mandliyarajendra11 feel free to fix if there is a bug

**Comment by naman0867** [comment]
Add link to path file
